# Product manifests are the sole source of firmware version identity.
set(identity_product "${LMDJ_SOURCE_ROOT}/products/lmdj")
file(READ "${identity_product}/version.json" identity_version)
file(READ "${LMDJ_SOURCE_ROOT}/apps/cardputer-host/module.json" identity_host)
file(READ "${identity_product}/assembly.lock.json" identity_lock)
set(identity_parts)
foreach(part milestone minor build patch)
  string(JSON value GET "${identity_version}" "${part}")
  list(APPEND identity_parts "${value}")
endforeach()
list(JOIN identity_parts "." LMDJ_CARDPUTER_PRODUCT_BUILD)
string(JSON LMDJ_CARDPUTER_HOST_VERSION GET "${identity_host}" version)
string(JSON LMDJ_CARDPUTER_ASSEMBLY_SHA256 GET "${identity_lock}" assembly_sha256)
string(JSON identity_locked_build GET "${identity_lock}" product version)
file(SHA256 "${identity_product}/assembly.json" identity_actual_sha)
if(NOT identity_locked_build STREQUAL LMDJ_CARDPUTER_PRODUCT_BUILD OR
   NOT identity_actual_sha STREQUAL LMDJ_CARDPUTER_ASSEMBLY_SHA256)
  message(FATAL_ERROR "why: Cardputer identity manifests disagree with Assembly lock; remedy: regenerate and verify the Product Assembly lock before building")
endif()
string(JSON identity_host_count LENGTH "${identity_lock}" hosts)
set(identity_host_found FALSE)
if(identity_host_count GREATER 0)
  math(EXPR identity_last_host "${identity_host_count} - 1")
  foreach(index RANGE ${identity_last_host})
    string(JSON identity_host_id GET "${identity_lock}" hosts ${index} id)
    if(identity_host_id STREQUAL "cardputer-host")
      string(JSON identity_locked_host GET "${identity_lock}" hosts ${index} version)
      if(NOT identity_locked_host STREQUAL LMDJ_CARDPUTER_HOST_VERSION)
        message(FATAL_ERROR "why: Cardputer Host version differs from Assembly lock; remedy: regenerate and verify the Product Assembly lock")
      endif()
      set(identity_host_found TRUE)
    endif()
  endforeach()
endif()
if(NOT identity_host_found)
  message(FATAL_ERROR "why: Cardputer Host is absent from Assembly lock; remedy: include the Host in the verified Product Assembly")
endif()
