// @vitest-environment node
//
// Forced to the `node` test environment (overriding the project-wide `jsdom`
// default in vite.config.ts) because Vite's static asset-URL transform
// special-cases the literal call pattern `new URL(x, import.meta.url)` and,
// under jsdom, rewrites it to resolve against `self.location`
// (http://localhost:3000/) instead of the module's real file:// URL — which
// breaks the node:fs reads below. This is a pure-Node contract test with no
// DOM dependency, so running it under `node` sidesteps the issue without
// changing the app-wide jsdom default other test files rely on.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { describe, expect, it } from "vitest";

const localSchemaUrl = new URL("./schema/lmdj.patch.v1.schema.json", import.meta.url);
const sourceSchemaUrl = new URL(
  "../../../../packages/core-models/lmdj_core_models/schemas/lmdj.patch.v1.schema.json",
  import.meta.url,
);
const typesUrl = new URL("./types.ts", import.meta.url);

const HEADER = `// GENERATED by npm run sync-contract — DO NOT EDIT.
// Source of truth: packages/core-models/lmdj_core_models/schemas/lmdj.patch.v1.schema.json
`;

describe("contract sync (npm run sync-contract)", () => {
  it("web schema copy is byte-identical to core-models source of truth", () => {
    const local = readFileSync(fileURLToPath(localSchemaUrl), "utf8");
    const source = readFileSync(fileURLToPath(sourceSchemaUrl), "utf8");
    expect(local).toBe(source);
  });

  it("types.ts is freshly generated from the schema", async () => {
    const schema = JSON.parse(readFileSync(fileURLToPath(localSchemaUrl), "utf8"));
    const expected = await compile(schema, "LmdjPatchV1", { bannerComment: HEADER });
    const actual = readFileSync(fileURLToPath(typesUrl), "utf8");
    expect(actual).toBe(expected);
  });
});
