// GENERATED by npm run sync-contract — DO NOT EDIT.
// Source of truth: packages/core-models/lmdj_core_models/schemas/lmdj.patch.v1.schema.json

/**
 * LMDJ product patch contract. Forward-compat rule: consumers MUST render unknown or reserved pad actions as disabled/no-op, never as errors. patch_id is a content-derived LOCAL identifier (song_id + sha256(lanes.json+chart.mid)[:8]); global identity is assigned by the platform layer — do not use patch_id as a database primary key. In v1 pipeline output, note velocity is always 100 (no dynamics information).
 */
export interface LmdjPatchV1 {
  schema: "lmdj.patch.v1";
  patch_id: string;
  source: {
    type: string;
    song_id?: string;
    [k: string]: unknown;
  };
  bpm: number;
  loop_seconds: number;
  elements: Element[];
  /**
   * @minItems 1
   */
  patterns: [Pattern, ...Pattern[]];
  /**
   * @minItems 16
   * @maxItems 16
   */
  pads: [Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad, Pad];
  /**
   * @minItems 1
   */
  scenes: [Scene, ...Scene[]];
  renders: Render[];
  metadata: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Element {
  element_id: string;
  name: string;
  kind: string;
  source_path: string;
  pitch: number;
  lane: number;
  role?: string | null;
  [k: string]: unknown;
}
export interface Pattern {
  pattern_id: string;
  name: string;
  source: {
    kind: string;
    path: string;
    [k: string]: unknown;
  };
  resolution: "1/16";
  length_steps: number;
  notes: Note[];
  [k: string]: unknown;
}
export interface Note {
  element_id: string;
  lane: number;
  pitch: number;
  step: number;
  velocity: number;
  [k: string]: unknown;
}
export interface Pad {
  index: number;
  slot: string;
  label: string;
  /**
   * trigger_element / trigger_group / empty are live in v1. scene_fill / scene_drop / mute_group / ai_variation are RESERVED: consumers must render them disabled and perform no action.
   */
  action: "trigger_element" | "trigger_group" | "empty" | "scene_fill" | "scene_drop" | "mute_group" | "ai_variation";
  element_id: string | null;
  behavior: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Scene {
  scene_id: string;
  name: string;
  /**
   * @minItems 16
   * @maxItems 16
   */
  pad_indexes: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ];
  pattern_ids: string[];
  intent: string;
  [k: string]: unknown;
}
export interface Render {
  kind: string;
  path: string;
  [k: string]: unknown;
}
