"""One durable official freeze, followed only by bounded resume verification.

Caller authenticates original authority, control/toolchain, main and reservation.
This local source-worktree transition is not a final cut, PR or release proof.
"""
from copy import deepcopy
from hashlib import sha256
import json
import os
from pathlib import Path

from .candidate_workspace import CandidateSourceWorkspace, FILES
from .model import canonical_json, canonical_sha256
from .orchestration import validate_request, JournalError
from .publication_workspace import PublicationWorkspaceError
from .task_verification import PublicationTaskVerifier, TaskVerificationError, verify_tracked_bytes


class CandidateSnapshotError(ValueError):
    pass


def require(value, reason):
    if not value:
        raise CandidateSnapshotError(f"why: candidate snapshot {reason}; remedy: retain the original worktree, reservation and command history; reconcile incomplete output without repeating generation or bypassing verification")


def read(journal, name, optional=False):
    journal._active()
    try:
        fd = os.open(name, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK, dir_fd=journal.directory)
    except FileNotFoundError:
        if optional:
            return None
        raise CandidateSnapshotError("why: candidate snapshot durable binding is missing; remedy: restore the original state; do not enroll another generation") from None
    try:
        journal._private(fd)
        with os.fdopen(fd, "rb", closefd=False) as stream:
            raw = stream.read(65537)
        value = json.loads(raw)
        require(len(raw) <= 65536 and canonical_json(value) == raw, "state is not bounded canonical JSON")
        return value
    finally:
        os.close(fd)


class CandidateSnapshotRun:
    def __init__(self, workspace, *, authorize, path, verification_limit=3):
        require(type(workspace) is CandidateSourceWorkspace, "requires the concrete source workspace")
        require(type(verification_limit) is int and 1 <= verification_limit <= 3, "verification budget is invalid")
        self.workspace, self.authorize, self.limit = workspace, authorize, verification_limit
        self.executor = PublicationTaskVerifier(None, workspace.root, authorize=authorize, path=path)
        self.path = path

    def _authorize(self, scope):
        try:
            self.authorize(deepcopy(scope))
        except Exception:
            raise CandidateSnapshotError("why: candidate snapshot authority is unavailable; remedy: restore the original authorization without replaying generation") from None

    def _checkout(self, source, fresh=False):
        local = self.workspace
        local._visible_index()
        require(local.git("symbolic-ref", "--short", "HEAD").decode().strip() == source["branch"], "source branch changed")
        require(local.revision("HEAD") == source["commit"]
                and local.revision("HEAD^{tree}") == source["tree"]
                and local.revision_from_index() == source["tree"], "source HEAD or index changed")
        try:
            verify_tracked_bytes(local, source["commit"],
                                 mutable_paths=() if fresh else ("apps/architecture-portal/versions.json",))
        except TaskVerificationError:
            require(False, "tracked source files changed")
        if fresh:
            require(not local.git("ls-files", "--others", "--exclude-standard", "-z"), "first freeze requires clean source")

    @staticmethod
    def _save(journal, state):
        raw = canonical_json({"state":state, "sha256":canonical_sha256(state)})
        require(len(raw) <= 65536, "state exceeds its durable read bound")
        journal._write("snapshot-state.json", raw)

    def _snapshot(self, source):
        local = self.workspace
        untracked = local.git("ls-files", "--others", "--exclude-standard", "-z")
        names = sorted({"apps/architecture-portal/versions.json"} | {name.decode() for name in untracked.split(b"\0") if name})
        require(0 < len(names) <= 512, "generated inventory is empty or exceeds its bound")
        result, total = [], 0
        for name in names:
            raw = local._file(name)
            require(raw is not None, "generated file disappeared")
            total += len(raw)
            require(total <= 64 * 1024 * 1024, "generated bytes exceed their bound")
            result.append({"path":name, "bytes":len(raw), "sha256":sha256(raw).hexdigest()})
        return result

    def run(self, request, source):
        try:
            return self._run(request, source)
        except (CandidateSnapshotError, JournalError, PublicationWorkspaceError, TaskVerificationError):
            raise
        except Exception:
            raise CandidateSnapshotError("why: candidate snapshot authority, state or execution is unavailable; remedy: inspect the retained private attempt and restore its original trusted source; never repeat generation") from None

    def _run(self, request, source):
        validate_request(request)
        source = deepcopy(source)
        require(source.pop("status", None) == "source-committed" and set(source.pop("files", [])) == FILES,
                "requires the completed source receipt")
        require(source.get("request_sha256") == canonical_sha256(request), "request differs from source binding")
        scope = {"request":deepcopy(request), "source":source, "channel":"canary",
                 "path":self.path, "verification_limit":self.limit}
        local = self.workspace
        gitdir = Path(local.git("rev-parse", "--absolute-git-dir").decode().strip())
        with local._locked(gitdir) as journal:
            require(read(journal, "binding.json") == source, "source differs from durable installation binding")
            self._authorize(scope)
            self._checkout(source)
            marker = read(journal, "snapshot-operation.json", optional=True)
            envelope = read(journal, "snapshot-state.json", optional=True)
            if marker is None:
                require(envelope is None, "state exists without original enrollment")
                self._checkout(source, fresh=True)
                journal._write("snapshot-operation.json", canonical_json(scope))
                state = {"schema":"lmdj.candidate-snapshot-run.v1", "scope":scope, "commands":[], "snapshot":None}
            else:
                require(marker == scope and type(envelope) is dict
                        and set(envelope) == {"state", "sha256"}, "enrollment changed or state disappeared")
                state = envelope["state"]
                require(canonical_sha256(state) == envelope["sha256"] and type(state) is dict
                        and set(state) == {"schema", "scope", "commands", "snapshot"}
                        and state["schema"] == "lmdj.candidate-snapshot-run.v1" and state["scope"] == scope,
                        "state digest or scope changed")
                require(type(state["commands"]) is list and 1 <= len(state["commands"]) <= 1 + self.limit,
                        "command inventory is invalid")
                for index, row in enumerate(state["commands"]):
                    require(type(row) is dict and set(row) == {"arguments", "result"}
                            and row["arguments"] == self._vector(source, index == 0), "command identity changed")
                    result = row["result"]
                    require(result is None or (type(result) is list and len(result) == 3
                        and type(result[0]) is int and -255 <= result[0] <= 255
                        and type(result[1]) is str and len(result[1]) == 64
                        and all(c in "0123456789abcdef" for c in result[1])
                        and type(result[2]) is int and result[2] >= 0), "command result is invalid")
                require(state["snapshot"] is None or state["snapshot"] == self._snapshot(source),
                        "previously verified snapshot bytes changed")
            # Enrollment persists before this first command intent. If the
            # controller dies in that gap, missing state refuses another freeze.
            if not state["commands"]:
                self._command(journal, state, source, generation=True)
            require(len(state["commands"]) < 1 + self.limit, "resume verification budget exhausted")
            self._command(journal, state, source, generation=False)
            inventory = self._snapshot(source)
            require(state["snapshot"] is None or state["snapshot"] == inventory,
                    "verified snapshot bytes changed during command")
            state["snapshot"] = inventory
            self._save(journal, state)
            return {"status":"snapshot-verified", "source_commit":source["commit"],
                    "product_build":source["product_build"],
                    "sha256":canonical_sha256({"source":source, "channel":"canary", "snapshot":inventory}),
                    "command_history_sha256":canonical_sha256(state)}

    @staticmethod
    def _vector(source, generation):
        return ["bash", "scripts/docs-site.sh", "version" if generation else "resume-version",
                source["product_build"], "canary", *([] if generation else [source["commit"]])]

    def _command(self, journal, state, source, *, generation):
        self._authorize(state["scope"])
        self._checkout(source, fresh=generation)
        row = {"arguments":self._vector(source, generation), "result":None}
        state["commands"].append(row)
        self._save(journal, state)
        result = self.executor._execute(journal, tuple(row["arguments"]), 900)
        row["result"] = list(result)
        self._save(journal, state)
        self._authorize(state["scope"])
        self._checkout(source)
        require(result[0] == 0, f"{row['arguments'][2]} exited {result[0]}")
